{
    "name": "iPhone 11 Pro Max 64GB",
    "display_technology": "OLED",
    "display_resolution": "1242 x 2688 Pixels",
    "display_size": "6.5 inches",
    "display_protection": "Kính cường lực oleophobic (ion cường lực)",
    "back_camera_resolution": "3 camera 12 MP",
    "back_camera_video": "Quay phim HD 720p@30fps, Quay phim FullHD 1080p@30fps, Quay phim FullHD 1080p@60fps, Quay phim FullHD 1080p@120fps, Quay phim FullHD 1080p@240fps, Quay phim 4K 2160p@24fps, Quay phim 4K 2160p@30fps, Quay phim 4K 2160p@60fps",
    "back_camera_flash": "4 đèn LED (2 tông màu)",
    "back_camera_advanced": "Ban đêm (Night Mode), Trôi nhanh thời gian (Time Lapse), Quay chậm (Slow Motion), Xoá phông, Góc rộng (Wide), Góc siêu rộng (Ultrawide), Tự động lấy nét (AF), Chạm lấy nét, Nhận diện khuôn mặt, HDR, Toàn cảnh (Panorama), Chống rung quang học (OIS)",
    "front_camera_resolution": "12 MP",
    "front_camera_videocall": True,
    "front_camera_other_infor": "   Xoá phông, Quay phim 4K, Nhãn dán (AR Stickers), Retina Flash, Quay video HD, Nhận diện khuôn mặt, Quay video Full HD, Tự động lấy nét (AF), HDR, Quay chậm (Slow Motion)"
    "operating_system": "iOS",
    "os_version": "iOS 13",
    "chipset": "Apple A13 Bionic 6 nhân",
    "cpu": "2 nhân 2.65 GHz & 4 nhân 1.8 GHz",
    "gpu": "Apple GPU 4 nhân",
    "ram": "4 GB",
    "memory_internal": "64 GB",
    "memory_available": "Khoảng 59 GB",
    "memory_card_slot":"Không",
    "mobile_network":"Hỗ trợ 4G",
    "sim": "1 eSIM & 1 Nano SIM",
    "Wifi": "Dual-band, Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot",
    "gps": "BDS, A-GPS, GLONASS",
    "bluetooth": "A2DP, LE, v5.0",
    "charging_port": "Lightning",
    "headphone_jack": "Lightning",
    "other_port": "NFC, OTG",
    "design": "Nguyên khối",
    "material": "Khung thép không gỉ & Mặt lưng kính cường lực",
    "dimensions": "Dài 158 mm - Ngang 77.8 mm - Dày 8.1 mm",
    "weight": "226 g",
    "battery_capacity": "3969 mAh",
    "battery_type": "Pin chuẩn Li-Ion",
    "battery_technology": "Tiết kiệm pin, Sạc pin nhanh, Sạc pin không dây",
    "advanced_security": "Mở khoá khuôn mặt Face ID",
    "special_features": "Đèn pin,Sạc pin không dây,Dolby Audio™,Chuẩn Kháng nước, Chuẩn kháng bụi,Sạc pin nhanh,Apple Pay",
    "recording": "Có, microphone chuyên dụng chống ồn",
    "radio": "Không",
    "watchfilm": "H.264(MPEG4-AVC)",
    "music": "Lossless, MP3, AAC, FLAC",
    "time_of_lunch": "11/2019"

}